### PR TITLE
fix: skip babel for qunit package when using embroider

### PR DESCRIPTION
**Pull request by pangratz**
This fixes the issue outlined in https://github.com/embroider-build/embroider/issues/677

### CODE REVIEW

**Comment by pangratz** [comment]
I changed the base to `master` so travis runs. Once it's green, I'll change the base again to target the upgrade PR

**Comment by pangratz** [comment]
Ok, seems travis is not picking up this PR since it originally wasn't targeting `master` 😔 

@LevelbossMike you wanna cherry-pick the last commit into your branch and see if that helps?

**Comment by pangratz** [comment]
OK, a force push afterwards did work so travis ran the PR. It's green 🙌 

I've changed base again so you can rebase this one on top of the upgrade PR

**Comment by LevelbossMike** [comment]
❤️  - great find! I think I was going crazy and tried to enable github-actions over travis in my branch.

**Comment by LevelbossMike** [comment]
sorry for being dumb - I clicked the rebase button on the wrong branch 🥇 -  cherry-picked your change onto master.

**Pull request closed without merging**
